### ISSUE TITLE
Autoscrolling options appear on print

### ISSUE THREAD

**Issue by ukozdan** [pinkienort/AutoScrolling#100]
**Describe the bug**
When printing within Firefox, the Autoscrolling add-on options are appended. 

**To Reproduce**
1. Navigate to menu > Print
2. Preview displays Autoscrolling add-on options page appended to end of document

**Expected behavior**
Autoscrolling add-on options page should not appear on any webpage print previews, unless that is the page one is intending on printing. 

**Screenshots**
[Google.pdf](https://github.com/pinkienort/AutoScrolling/files/2613294/Google.pdf)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser Firefox 63.0.3
 - Version: 1.5.9

**Additional context**

**Comment by hisakaz0** [comment]
https://stackoverflow.com/questions/355313/how-do-i-hide-an-element-when-printing-a-web-page

**Comment by hisakaz0** [comment]
@ukozdan 
I will take the bugfix in next release 1.5.10.
Relase date: TBA

**Comment by hisakaz0** [comment]
@ukozdan 
I released a new version which is fixed above the bug. 👍 
https://addons.mozilla.org/ja/firefox/addon/autoscrolling/
