### ISSUE TITLE
i need speed

### ISSUE THREAD

**Issue by ghost** [pinkienort/AutoScrolling#2]
i need speed without limits, this is possible?

**Comment by hisakaz0** [comment]
Of course 👍

**Comment by ghost** [comment]
when the limit of the 99 will be broken?

**Comment by hisakaz0** [comment]
It is need to change source code which controls the scrolling speed.
Current source code  is following.
When parameter `step` is bigger than 1, speed is accelerated.
But I want one parameter only which user can control.

@aicoutos  Do you have a good opinion?

``` 
 step: 1,
 start: function () {
    this.y = this.y + this.step;
    this.scrollingElement.scroll(this.x, this.y);
    this.tid = setTimeout(() => {
      this.start();
    }, 100 - this.speed);
},
```

**Comment by ghost** [comment]
@pinkienort theoretically (i don't tested this) you can maintain only one parameter removing the setTimeout function and adding a while loop for numbers above 99 for free speed . 

NOTE: setTimeout is [limited to 4ms](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timers) in the HTML5. 
```js
 step: 1,
 start: function () {
    this.y = this.y + this.step;
    this.scrollingElement.scroll(this.x, this.y);
    if(this.speed<99){
      this.tid = setTimeout(() => {
        this.start();
      }, 100 - this.speed);
    }else{
      while(autoScrolling.stopByClick==true){
        this.start();
      }
    }
},
```
