### ISSUE TITLE
Option: Automatically pause scrolling when mouse hovers text

### ISSUE THREAD

**Issue by resolritter** [pinkienort/AutoScrolling#5]
What do you think @pinkienort ?

Mouse enters text: Autoscrolling is paused
Mouse leaves text: Autoscrolling is resumed

**Comment by hisakaz0** [comment]
@jpsouzasilva Sound good.
I think too. When this function is added to the add-on, the function should be option.

**Comment by resolritter** [comment]
Okay, I'll be doing this one on https://github.com/jpsouzasilva/AutoScrolling/tree/stop-scrolling-hover
